
[[constraint]]
  branch = "master"
  name = "github.com/viacoin/viad"

[[constraint]]
  name = "github.com/jessevdk/go-flags"
  version = "1.4.0"

[[constraint]]
  name = "github.com/miekg/dns"
  version = "1.0.5"

[prune]
  go-tests = true
  unused-packages = true
